// AUTO-GENERATED FILE. Do not edit directly.
// Generated from public/json-packs/*.json

export const AUDIO = {
  FOREST_AMBIENT: 'forest-ambient',
  CAVE_AMBIENT: 'cave-ambient',
  FIREBALL_LAUNCH: 'fireball-launch',
  FIREBALL_IMPACT: 'fireball-impact',
  FIREBALL_CRIT_IMPACT: 'fireball-crit-impact',
  BLINK_ACTION: 'blink-action',
  WIND_ACTION: 'wind-action',
  FROSTBOLT_LAUNCH: 'frostbolt-launch',
  FROSTBOLT_IMPACT: 'frostbolt-impact',
  LIGHTNING_SHIELD_ACTION: 'lightning-shield-action',
  LIGHTNING_SHIELD_ABSORB: 'lightning-shield-absorb',
  EARTH_SHAKE_LAUNCH: 'earth-shake-launch',
  EARTH_SHAKE_IMPACT: 'earth-shake-impact',
  SHADOWBOLT_LAUNCH: 'shadowbolt-launch',
  SHADOWBOLT_IMPACT: 'shadowbolt-impact',
  SHADOW_TRAIL_DISAPPEARS: 'shadow-trail-disappears',
  SHADOW_TRAIL_APPEARS: 'shadow-trail-appears',
  SWORD_IMPACT: 'sword-impact',
  UNARMED_IMPACT: 'unarmed-impact',
  ARROW_LAUNCH: 'arrow-launch',
  ARROW_IMPACT: 'arrow-impact',
  BAT_IMPACT: 'bat-impact',
  FREEZE: 'freeze',
  PROTECTION: 'protection',
  HEALING: 'healing',
  UNDYING: 'undying',
  SPELL_POWER: 'spell-power',
  HASTE: 'haste',
  CONCENTRATION: 'concentration',
  CASTING: 'casting',
  COIN_PICK: 'coin-pick',
  COIN_BUY: 'coin-buy',
  BOARD_OPEN: 'board-open',
  BOARD_CLOSE: 'board-close',
  STORE_OPEN: 'store-open',
  STORE_CLOSE: 'store-close',
  PAPER_OPEN: 'paper-open',
  PAPER_CLOSE: 'paper-close',
  CHEST_OPEN: 'chest-open',
  SPEAR_IMPACT: 'spear-impact',
  SKELETON_WARRIOR_AGGRO: 'skeleton-warrior-aggro',
  ZOMBIE_AGGRO: 'zombie-aggro',
  FIREWORM_AGGRO: 'fireworm-aggro',
  BAT_AGGRO: 'bat-aggro',
  ENEMY_AGGRO_1: 'enemy-aggro-1',
  ENEMY_AGGRO_2: 'enemy-aggro-2',
  ENEMY_AGGRO_3: 'enemy-aggro-3',
  ENEMY_AGGRO_4: 'enemy-aggro-4',
  ENEMY_AGGRO_5: 'enemy-aggro-5',
  ENEMY_AGGRO_6: 'enemy-aggro-6',
  ENEMY_AGGRO_7: 'enemy-aggro-7',
  ENEMY_AGGRO_8: 'enemy-aggro-8',
  ENEMY_AGGRO_9: 'enemy-aggro-9',
  ENEMY_AGGRO_10: 'enemy-aggro-10',
} as const;

export const BACKGROUNDS = {
  MAIN_SCENE_BG: 'main-scene-bg',
  FOREST_FRONT_BG: 'forest-front-bg',
  FOREST_BACK_BG: 'forest-back-bg',
  MOUNTAIN_RANGE_BG: 'mountain-range-bg',
  SKY_BG: 'sky-bg',
} as const;

export const CHARACTERS = {
  PLAYER: 'player',
  ALCHEMIST: 'alchemist',
  SKELETON_WARRIOR: 'skeleton-warrior',
  ZOMBIE: 'zombie',
  ARCHER: 'archer',
  MUTATED_BAT: 'mutated-bat',
  FIRE_WORM: 'fire-worm',
  EVIL_WIZARD: 'evil-wizard',
} as const;

export const ITEMS = {
  COIN: 'coin',
} as const;

export const MAPS = {
  LEVEL_1: 'level-1',
  UI_LEVEL: 'ui-level',
} as const;

export const MISC = {
  SOUL_FIRE: 'soul-fire',
  BONFIRE: 'bonfire',
  BOWLER: 'bowler',
  CRYSTAL_SHRINE: 'crystal-shrine',
  PORTAL: 'portal',
  DARK_ENERGY: 'dark-energy',
  SHINING: 'shining',
  QUEST_MARK: 'quest-mark',
  SIGN_MARK: 'sign-mark',
  LETTER: 'letter',
  GAME_TITLE: 'game-title',
} as const;

export const OBJECTS = {
  CONIFER: 'conifer',
  STORE: 'store',
  BONFIRE_OFF: 'bonfire-off',
  BOTTLES: 'bottles',
  STATUE_LEFT: 'statue-left',
  STATUE_RIGHT: 'statue-right',
  WOOD: 'wood',
  BOXES: 'boxes',
  APPLE_TABLE: 'apple-table',
  TABLE: 'table',
  TENT: 'tent',
  STUMP: 'stump',
  CRYSTAL_WHITE: 'crystal-white',
  CRYSTAL_RED: 'crystal-red',
  ROCK_1: 'rock-1',
  ROCK_2: 'rock-2',
  ROCK_3: 'rock-3',
  ROCK_4: 'rock-4',
  ROCK_5: 'rock-5',
  ROCK_6: 'rock-6',
  ROCK_7: 'rock-7',
  BUSH_1: 'bush-1',
  BUSH_2: 'bush-2',
  BUSH_3: 'bush-3',
  CHEST_CLOSE: 'chest-close',
  CHEST_OPEN: 'chest-open',
} as const;

export const SPELLS = {
  FIRE_BALL: 'fire-ball',
  BLINK: 'blink',
  LIGHTNING_SHIELD: 'lightning-shield',
  WIND_WAVE: 'wind-wave',
  FROST_BOLT: 'frost-bolt',
  SHADOW_BOLT: 'shadow-bolt',
  EARTH_SHAKE: 'earth-shake',
  SHADOW_TRAIL: 'shadow-trail',
} as const;

export const TILESETS = {
  ANCIENT_TILES: 'ancient-tiles',
  GROUND_TILES: 'ground-tiles',
  CLIFF_TILES: 'cliff-tiles',
  DIRT_TILES: 'dirt-tiles',
  GRASS_TILES: 'grass-tiles',
} as const;

export const UI = {
  INVENTORY_SLOT: 'inventory-slot',
  CONTROL_SLOT: 'control-slot',
  FIRE_BALL_ICON: 'fire-ball-icon',
  BLINK_ICON: 'blink-icon',
  WIND_ICON: 'wind-icon',
  FROSTBOLT_ICON: 'frostbolt-icon',
  COIN_UI: 'coin-ui',
  HEALTH_BAR: 'health-bar',
  HEALTH_ENV: 'health-env',
  CAST_BAR: 'cast-bar',
  CAST_BAR_GREEN: 'cast-bar-green',
  CAST_ENV: 'cast-env',
  BOSS_HEALTH_BAR: 'boss-health-bar',
  BOSS_HEALTH_ENV: 'boss-health-env',
  QUEST_LOG_UI: 'quest-log-ui',
  ASIDE_UI: 'aside-ui',
  QUEST_LOG_CLOSE_BTN_UI: 'quest-log-close-btn-ui',
  STORE_UI: 'store-ui',
  STORE_UI_CLOSE_BUTTON: 'store-ui-close-button',
  ITEM_CARD: 'item-card',
  QUEST_UI: 'quest-ui',
  QUEST_UI_ACCEPT_BTN: 'quest-ui-accept-btn',
  QUEST_UI_DECLINE_BTN: 'quest-ui-decline-btn',
  QUEST_UI_COMPLETE_BTN: 'quest-ui-complete-btn',
  LETTER_UI: 'letter-ui',
  LETTER_UI_CLOSE_BTN: 'letter-ui-close-btn',
  DIALOG_UI: 'dialog-ui',
  DIALOG_UI_BUTTON_YES: 'dialog-ui-button-yes',
  DIALOG_UI_BUTTON_NO: 'dialog-ui-button-no',
  MENU_UI_START_BTN: 'menu-ui-start-btn',
  MENU_UI_CONTINUE_BTN: 'menu-ui-continue-btn',
  MENU_UI_OPTION_BTN: 'menu-ui-option-btn',
  MENU_UI_CREDITS_BTN: 'menu-ui-credits-btn',
  GEAR_CONTROL: 'gear-control',
  CLOUD_CONTROL: 'cloud-control',
  TROPHY_CONTROL: 'trophy-control',
  PAUSE_UI_RESUME_BTN: 'pause-ui-resume-btn',
  PAUSE_UI_MAIN_MENU_BTN: 'pause-ui-main-menu-btn',
  EDGE_BOARD: 'edge-board',
  MISC_UI_OK_BTN: 'misc-ui-ok-btn',
  INFO_BUTTON: 'info-button',
  MISC_UI_BACK_BTN: 'misc-ui-back-btn',
  MISC_UI_PLUS_BTN: 'misc-ui-plus-btn',
  MISC_UI_MINUS_BTN: 'misc-ui-minus-btn',
  MISC_UI_DLT_SAVE_DATA_BTN: 'misc-ui-dlt-save-data-btn',
  CURSOR: 'cursor',
  HEALTH_POTION_ICON: 'health-potion-icon',
  NATURE_POTION_ICON: 'nature-potion-icon',
  PROTECTION_POTION_ICON: 'protection-potion-icon',
  SPELL_POTION_ICON: 'spell-potion-icon',
  LIGHTNING_POTION_ICON: 'lightning-potion-icon',
  UNDYING_POTION_ICON: 'undying-potion-icon',
  HASTE_POTION_ICON: 'haste-potion-icon',
  FIRE_RELIC_ICON: 'fire-relic-icon',
  FROST_RELIC_ICON: 'frost-relic-icon',
  SOUL_STONE_ICON: 'soul-stone-icon',
  STONE_OF_CONCENTRATION_ICON: 'stone-of-concentration-icon',
  PROTECTION_BUFF: 'protection-buff',
  SPELL_POWER_BUFF: 'spell-power-buff',
  LIGHTNING_SHIELD_BUFF: 'lightning-shield-buff',
  UNDYING_BUFF: 'undying-buff',
  ARCANE_MIND_BUFF: 'arcane-mind-buff',
  HASTE_BUFF: 'haste-buff',
  CONCENTRATION_BUFF: 'concentration-buff',
  FIRE_ENERGY_BUFF: 'fire-energy-buff',
  FROST_SKIN_BUFF: 'frost-skin-buff',
  CRYSTAL_RENEWAL_BUFF: 'crystal-renewal-buff',
  FROSTBITE_DEBUFF: 'frostbite-debuff',
  DISEASE_DEBUFF: 'disease-debuff',
  DREAD_AURA_DEBUFF: 'dread-aura-debuff',
  SHADOW_VULNERABILITY_DEBUFF: 'shadow-vulnerability-debuff',
  FIREWORM_FANG_QUEST_ITEM: 'fireworm-fang-quest-item',
  CRYSTAL_QUEST_ITEM: 'crystal-quest-item',
} as const;

export const VFX = {
  FREEZE_VFX: 'freeze-vfx',
  RESPAWN_VFX: 'respawn-vfx',
  HEAL_VFX: 'heal-vfx',
  PROTECTION_VFX: 'protection-vfx',
  SPELL_VFX: 'spell-vfx',
  UNDYING_VFX: 'undying-vfx',
  ARCANE_MIND_VFX: 'arcane-mind-vfx',
  HASTE_VFX: 'haste-vfx',
  CONCENTRATION_VFX: 'concentration-vfx',
  EARTH_ANXIETY_VFX: 'earth-anxiety-vfx',
  EVIL_WIZARD_DISAPPEARS_VFX: 'evil-wizard-disappears-vfx',
  EVIL_WIZARD_APPEARS_VFX: 'evil-wizard-appears-vfx',
} as const;

export const WEAPONS = {
  ARROW: 'arrow',
} as const;
