export const ITEM_COSTS = {
  HEALTH_POTION: 2,
  PROTECTION_POTION: 4,
  SPELL_POTION: 5,
  LIGHTNING_POTION: 5,
  UNDYING_POTION: 8,
  SOUL_STONE: 10,
} as const;

/*export const ITEM_COSTS = {
  HEALTH_POTION: 0,
  PROTECTION_POTION: 0,
  SPELL_POTION: 0,
  LIGHTNING_POTION: 0,
  UNDYING_POTION: 0,
  SOUL_STONE: 0,
} as const;*/
